x-common-settings: &common-settings
  volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  environment:
    TZ: Asia/Taipei
    MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
  restart: always
  networks:
    - mariaNet

services:
  db:
    <<: *common-settings
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  backup:
    <<: *common-settings
    image: mysql
    volumes:
      - ./backup.sh:/backup.sh
      - ./backup:/backup
      - ./log:/log
    environment:
      DB_HOST: db
      BACKUP_DIR: /backup
      EVERY_N_HR_BACKUP: ${EVERY_N_HR_BACKUP}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    depends_on:
      - db
    entrypoint: /bin/sh -c "
      chmod +x /backup.sh && \
      while true; do \
        /backup.sh >> /log/backup_$(date +\%Y\%m\%d_\%H\%M\%S).log 2>&1; \
        sleep $((${EVERY_N_HR_BACKUP} * 3600)); \
      done"

  phpmyadmin:
    <<: *common-settings
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

networks:
  mariaNet: